CREATE TABLE spec_tbl (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
            name VARCHAR(128) NOT NULL,
            version VARCHAR(32),
            created_date DATE,
            lastUpdated_date DATE);