CREATE TABLE respbody_tbl (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
            body LONGVARCHAR NOT NULL,
            created_date DATE,
            lastUpdated_date DATE);