CREATE TABLE contenttype_tbl (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
            content_type VARCHAR(128) NOT NULL,
            created_date DATE,
            lastUpdated_date DATE);